### ISSUE TITLE
Publish on Firefox Add-On Portal

### ISSUE THREAD

**Issue by jtojnar** [ageitgey/show-facebook-computer-vision-tags#11]
https://addons.mozilla.org/en-US/developers/addon/submit/distribution

**Comment by jtojnar** [comment]
The `applications` key was only required by older versions of Firefox, the extension is compatible even without it.

Extension can be generated using [web-ext](https://github.com/mozilla/web-ext) tool or you can just upload the zipball.

**Comment by ageitgey** [comment]
I submitted it. We'll see if it gets approved:

<img width="172" alt="screen shot 2017-01-02 at 3 52 22 pm" src="https://cloud.githubusercontent.com/assets/896692/21597687/8accbed2-d103-11e6-9ce1-b81f22e80d7d.png">

**Comment by ageitgey** [comment]
Done!

https://addons.mozilla.org/en-US/firefox/addon/show-computer-vision-tags/
