### ISSUE TITLE
Emoji is not working in chrome extension

### ISSUE THREAD

**Issue by ramytamer** [ageitgey/show-facebook-computer-vision-tags#30]
I am using Chrome 55.0.2883.87 (64-bit) on Ubuntu 14.04

![image](https://cloud.githubusercontent.com/assets/7445123/21751971/9cbb26f4-d5d8-11e6-99a1-98cc25b25d76.png)

**Comment by ageitgey** [comment]
Works fine for me in Ubuntu. But the version I'm using isn't as old as 14.04. Maybe the issue is the fonts available in the older version not having the emoji?

![ubuntu](https://cloud.githubusercontent.com/assets/896692/21757896/1e07c9ea-d5ea-11e6-8d49-776fe023e1d5.png)

**Comment by elamperti** [comment]
Doesn't work for me either. It depends on having a emoji font installed properly, and in some operating systems (linux, old versions of windows) it may be tricky to get that working. It would be nice to have [twemoji](https://github.com/twitter/twemoji) or something similar as a backup alternative (toggleable from options or enabled by default).

**Comment by jtojnar** [comment]
Would it be possible to use Facebook’s emoji directly? On a first sight I am not sure what the three-letter part of URL is.

* https://www.facebook.com/images/emoji.php/v6/zce/1/16/1f600.png
* https://www.facebook.com/images/emoji.php/v6/fcb/1/16/1f641.png
* https://www.facebook.com/images/emoji.php/v6/f57/1/16/1f609.png

Maybe there is some JavaScript API.
