### ISSUE TITLE
Publish on Chrome Web Store

### ISSUE THREAD

**Issue by alshakero** [ageitgey/show-facebook-computer-vision-tags#4]
Hello,

Why not publish the extension on the store? When you install an extension the way you mention, Chrome keeps complaining that it's bad for you to do so with every launch.

**Comment by ageitgey** [comment]
I've submitted it. It should hopefully show up shortly. Thanks!

**Comment by ageitgey** [comment]
Here: https://chrome.google.com/webstore/detail/show-facebook-computer-vi/elafbihhbfmfihdflghclaclcilcnmie?hl=en-US&gl=US
