### ISSUE TITLE
It doesn't work on facebook's url that is "https://web.facebook.com"

### ISSUE THREAD

**Issue by dumpsayamrat** [ageitgey/show-facebook-computer-vision-tags#51]
[show-facebook-computer-vision-tags](https://github.com/ageitgey/show-facebook-computer-vision-tags)  doesn't work on facebook's url that is "https://web.facebook.com".

Sometimes when I visit facebook with [https://www.facebook.com](https://www.facebook.com), Facebook will automatically redirect to [https://web.facebook.com](https://web.facebook.com) and [show-facebook-computer-vision-tags](https://github.com/ageitgey/show-facebook-computer-vision-tags) extension doesn't work. I think you might need to fix manifest file. :)

And also I would like to translate for Thai version, Can I do?

Thanks.

**Comment by ageitgey** [comment]
I've never seen web.facebook.com before. It just redirects to www.facebook.com from here. So I wasn't aware of it.

Sure, please feel free to submit a PR for a Thai translation and to fix the manifest if you can test it from your side!

**Comment by dumpsayamrat** [comment]
Fixed.
