### ISSUE TITLE
Non-blocking error on installation

### ISSUE THREAD

**Issue by kjrrp** [ageitgey/show-facebook-computer-vision-tags#6]
When loading the unpacked extension, Chrome prints this error:

```
There were warnings when trying to install this extension:
* Unrecognized manifest key 'applications'.
```
The extension still works though.

v 0.1

Chrome Version 55.0.2883.87 (64-bit)

**Comment by SpEcHiDe** [comment]
I think the problem is with this line: https://github.com/ageitgey/show-facebook-computer-vision-tags/blob/master/manifest.json#L20

**Comment by nullbio** [comment]
Getting this as well.

**Comment by ageitgey** [comment]
I removed the Firefox nightly support since it causes this error.
